services:
  woocommerce-mcp:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.http-bridge
    environment:
      - PORT=8090
      - GIN_MODE=release
    networks:
      - shared_network
    expose:
      - "8090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  shared_network:
    external: true
